version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - aws s3 cp s3://$AUTH_PATH auth.json
      - ./mvnw exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"
      - ./mvnw test

